### ISSUE TITLE
Update Gem on RubyGems.org

### ISSUE THREAD

**Issue by magnuslarsen** [voxpupuli/puppet_webhook#122]
Hello,

Is it possible that you could update the gem on rubygems.org, to the newest 2.x release?
Currently only the legacy (end of life) version is downloadable from rubygems.org :/

I'd rather manage my ruby applications using gems, over tar.

Thanks!

**Comment by nmollerup** [comment]
:+1:

**Comment by dhollinger** [comment]
The 2.x version is built using Sinatra/Rails standards, which includes having a `Gemfile.lock` to lock the dependencies for the application. There will not be a gem version for the newer 2.x

That said, if you take a look at the README changes merged today (and a forthcoming blog post), we now have Deb and RPM packages and associated APT and YUM repos for installing puppet-webhook >= 2.x
