### ISSUE TITLE
Logging doesn't appear to be working anymore.

### ISSUE THREAD

**Issue by binford2k** [voxpupuli/puppet_webhook#146]
Perhaps we need to pass a log object to r10k as in https://github.com/puppetlabs/bolt/commit/2b04550edd094de490892d1b6733cddfa2070501

**Comment by dhollinger** [comment]
Current issue is that when the r10k libraries are called, the logging gets eaten by the app. Instead, we need to look into shimming a way to pass/utilize r10k's logging within puppet_webhook to ensure that events are logged.
