### ISSUE TITLE
Implement redis auth support

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet_webhook#159]
At the moment, puppet_webhook requires a redis instance on localhost. https://medium.com/@Victor.Z.Zhu/redis-unauthorized-access-vulnerability-simulation-victor-zhu-ac7a71b2e419 currently floats around in american companies and security teams are scared about redis without authentication.

I don't think that our specific setup is vulnerable. Redis runs on localhost only, it runs with a dedicated user that has /sbin/nologin as shell and people can firewall the redis and sshd port. Based on that it's not possible to write to redis from an external server. But even if someone does it because people bind redis to the public interface by accident, you can only overwrite the ssh file from the redis user and that user isn't able to login via ssh due to the nonexisting shell...

To please security people we should nevertheless implement redis authentication.

**Comment by dhollinger** [comment]
I think the better solution is to add support for remote redis configuration with an auth option.

**Comment by igalic** [comment]
i agree with @dhollinger on this one

local only access that's heavily secured otherwise shouldn't need authentication

but remote access definitely does
