### ISSUE TITLE
Build RPM/DEB/Arch Packages

### ISSUE THREAD

**Issue by dhollinger** [voxpupuli/puppet_webhook#25]

**Comment by rnelson0** [comment]
It’s pretty ugly, but I use this to build some RPMs for other projects. Adding other output formats is easy, just need to know how to generate the not-yet-a-package in a temporary directory. https://github.com/rnelson0/build_reference

**Comment by ekohl** [comment]
https://github.com/fedora-ruby/gem2rpm is probably the easiest way to build RPMs.

**Comment by mterzo** [comment]
I’m using fpm to build rpms. 

https://github.com/jordansissel/fpm/blob/master/README.rst

**Comment by bastelfreak** [comment]
For Archlinux I would use https://github.com/anatol/gem2arch

**Comment by rnelson0** [comment]
Is there a particular reason to use gem2rpm and gem2arch vs fpm which can
do both? I am sure there are differences in the generated packages but am
not aware of how that impacts the results.

**Comment by bastelfreak** [comment]
gem2arch is a more common approach to create archlinux packages, fpm isn't. So I would use gem2arch to do it.

**Comment by ekohl** [comment]
fpm create very ugly packages that technically work, but that's it. They're far from native packages where the gem2* packages create packages that could actually pass a review from other packagers.

**Comment by alexjfisher** [comment]
I've used fpm too.  Great for in-house packages.  Not so good for packages we want to distribute.
